# Generated by Django 2.1.5 on 2019-01-10 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clean_blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descriptions',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
