# Generated by Django 2.1.5 on 2019-01-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean_blog_app', '0002_post_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='headerSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image_header', models.ImageField(upload_to=None)),
                ('subheading', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_text', models.CharField(max_length=50)),
                ('logo_img', models.ImageField(upload_to='logo/picture')),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.URLField()),
                ('about', models.URLField()),
                ('simple_page', models.URLField()),
                ('contact', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='author',
            old_name='image',
            new_name='image_auth',
        ),
    ]
