# Generated by Django 2.1.5 on 2019-01-11 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clean_blog_app', '0004_post_part_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default=django.utils.timezone.now, height_field=693, upload_to='post/images', width_field=1391),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='headersection',
            name='image_header',
            field=models.ImageField(height_field=532, upload_to='header/pic', width_field=1351),
        ),
    ]
